server:
  port: 8084

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/notification
  redis:
    host: redis
    port: 6379
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true